name: Run Bookings

on:
  #schedule:
  #  - cron: "58 20 * * *"   # 4:59 PM Montreal
  #  - cron: "58 21 * * *"   # 5:59 PM Montreal
  #  - cron: "58 22 * * *"   # 6:59 PM Montreal
  #  - cron: "58 23 * * *"   # 7:59 PM Montreal
  workflow_dispatch:         # 👈 manual trigger option

jobs:
  run-bookings:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        script: [final_booking_tommy.py, final_booking_sylvia.py, final_booking_ricky.py, final_booking__calvin.py]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # ✅ Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 👀 Debug pip cache status
      - name: Show pip cache status
        run: du -sh ~/.cache/pip || echo "No pip cache restored"

      # ✅ Cache Playwright browsers
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
          restore-keys: |
            ${{ runner.os }}-playwright

      # 👀 Debug Playwright cache status
      - name: Show Playwright cache status
        run: du -sh ~/.cache/ms-playwright || echo "No Playwright cache restored"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium

      - name: Run booking script
        env:
          HEADLESS: "true"
          PYTHONUNBUFFERED: "1"
          TZ: America/Toronto
        run: python -u ${{ matrix.script }}
