name: Pickleball Automation

on:
  schedule:
    - cron: "0 20 * * *"    # 4:00 PM Montreal (20:00 UTC) -> run read_slots.py
    - cron: "59 20 * * *"   # 4:59 PM Montreal (20:59 UTC) -> run booking scripts
    - cron: "59 21 * * *"   # 5:59 PM Montreal (21:59 UTC)
    - cron: "59 22 * * *"   # 6:59 PM Montreal (22:59 UTC)
    - cron: "59 23 * * *"   # 7:59 PM Montreal (23:59 UTC)
  workflow_dispatch:

jobs:
  update-slots:
    if: github.event.schedule == '0 20 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run read_slots.py
        run: python read_slots.py

      - name: Commit updated slots.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add slots.json
          git commit -m "Auto-update slots.json [$(date)]" || echo "No changes to commit"
          git push

  run-bookings:
    if: github.event.schedule == '59 20 * * *' || github.event.schedule == '59 21 * * *' || github.event.schedule == '59 22 * * *' || github.event.schedule == '59 23 * * *'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [final_booking_tommy.py, final_booking_sylvia.py, final_booking_ricky.py, final_booking__calvin.py]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run booking script
        run: python ${{ matrix.script }}
